name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'docker-bake.hcl'
      - '.github/workflows/build.yml'
      - 'scripts/**'
      - 'proxy/**'
      - 'services/**'
      - 'presets/**'
      - 'README.md'
  workflow_dispatch:
    inputs:
      extra_tag:
        description: "Дополнительный суффикс тега (например, -dev или -2025-10-14)"
        required: false
        default: ""

env:
  DOCKERHUB_REPO_NAME: smyshnikof/comfyui-wan

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print context & check secrets length
        run: |
          echo "ref=$GITHUB_REF sha=$GITHUB_SHA repo=$GITHUB_REPOSITORY"
          ulen=${#DOCKERHUB_USERNAME}
          tlen=${#DOCKERHUB_TOKEN}
          echo "DOCKERHUB_USERNAME length: $ulen"
          echo "DOCKERHUB_TOKEN length: $tlen"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Validate Docker Hub secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then echo "Missing secret: DOCKERHUB_USERNAME" && exit 1; fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "Missing secret: DOCKERHUB_TOKEN" && exit 1; fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bake and push images
        uses: docker/bake-action@v6
        with:
          files: |
            docker-bake.hcl
          targets: |
            base-12-4
            base-12-5
            base-12-6
            base-12-8
            base-12-9
            base-13-0
          push: true
        env:
          DOCKERHUB_REPO_NAME: ${{ env.DOCKERHUB_REPO_NAME }}
          EXTRA_TAG: ${{ github.event.inputs.extra_tag }}

name: Build and Push Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  bake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [base]
        cuda: [12-4, 12-6, 12-8]
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          targets: ${{ matrix.target }}-${{ matrix.cuda }}
          push: true
