name: Build and Push Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  bake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [base]
        cuda: [12-4, 12-6, 12-8]
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug secrets length
        run: |
          ulen=${#DOCKERHUB_USERNAME}
          tlen=${#DOCKERHUB_TOKEN}
          echo "DOCKERHUB_USERNAME length: $ulen"
          echo "DOCKERHUB_TOKEN length: $tlen"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker login (Docker Hub)
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          targets: ${{ matrix.target }}-${{ matrix.cuda }}
          push: true

